In [69]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import OneClassSVM
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, classification_report, recall_score, ConfusionMatrixDisplay, make_scorer
from sklearn.model_selection import RandomizedSearchCV, train_test_split, cross_validate, StratifiedKFold, cross_val_predict
import numpy as np
import common

dataset, label = common.load_dataset()

label.value_counts()

(-, source, mc)
2    261116
0      5979
Name: count, dtype: int64

In [ ]:
rf = RandomForestClassifier()

dataset, label = common.load_dataset()

X_train, X_test, y_train, y_test = train_test_split(dataset, label, test_size=0.8)

scoring = ['precision_macro', 'recall_macro']
scores = cross_validate(clf, dataset, label, scoring=scoring)

rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)

print(classification_report(y_test, y_pred))

In [73]:
def fpr(y, y_pred):
    false_positives = (y_pred[y == 0] > 0).sum()
    return false_positives / (y == 0).shape[0]

def fp(y, y_pred):
    return (y_pred[y == 0] > 0).sum()
    
def cm(y, y_pred):
    cm = confusion_matrix(y, y_pred)
    return {'tn': cm[0, 0], 'fp': cm[0, 1],
             'fn': cm[1, 0], 'tp': cm[1, 1]}
    
rf = RandomForestClassifier()

dataset, label = common.load_dataset()

dataset = dataset.iloc[0:10000]
label = label.iloc[0:10000]

skf = StratifiedKFold(n_splits=5)

scoring = {'prec_macro': 'precision_macro',
           'rec_macro': make_scorer(fpr),
            "fp": make_scorer(fp),
           "cm": make_scorer(cm)
          }

predictions = cross_val_predict(rf, dataset, label, cv=skf)

print(predictions)

[2 2 2 ... 0 0 0]


In [78]:
len(predictions)

10000

In [74]:
dataset, label = common.load_dataset()

for i in range(5):
    _labels = label.iloc[scores['indices']['train'][i]]
    print((_labels == 0).sum(), (_labels > 0).sum())
    _labels = label.iloc[scores['indices']['test'][i]]
    print((_labels == 0).sum(), (_labels > 0).sum())
    print(scores["train_rec_macro"][i])
    print(scores["train_fp"][i])
    print(scores["test_rec_macro"][i])
    print(scores["test_fp"][i])
    print()

3774 4226
943 1057
0.0
0
0.0995
199

3774 4226
943 1057
0.0
0
0.044
88

3774 4226
943 1057
0.0
0
0.0
0

3773 4227
944 1056
0.0
0
0.0
0

3773 4227
944 1056
0.0
0
0.0015
3



In [73]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8)
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(classification_report(y_test, y_pred))

RandomForestClassifier()

In [140]:

x_cols = [
#     (  '-',           '-',      'n_message'),
#     (  '-',           '-',     'fn_req_min'),
#     (  '-',           '-',     'fn_req_max'),
#     (  '-',           '-',   'time_s_start'),
#     (  '-',           '-',     'time_s_end'),
#     (  '-',           '-',     'duration'),
#     (  '-',           '-',             'qr'),
#     (  '-',           '-',              'u'),
#     (  '-',           '-',              'q'),
#     (  '-',           '-',              'r'),
#     (  '-',           '-',             'nx'),
#     (  '-', 'whitelisted',              '0'),
#     (  '-', 'whitelisted',             '100'),
#     (  '-', 'whitelisted',             '1000'),
#     (  '-', 'whitelisted',             '1000000'),
#     ('eps',        'NONE', '[0.000, 0.100)'),
#     ('eps',        'NONE', '[0.100, 0.250)'),
#     ('eps',        'NONE', '[0.250, 0.500)'),
#     ('eps',        'NONE', '[0.500, 0.900)'),
#     ('eps',        'NONE', '[0.900, 1.100)'),
    ('eps',         'TLD', '[0.000, 0.100)'),
    ('eps',         'TLD', '[0.100, 0.250)'),
    ('eps',         'TLD', '[0.250, 0.500)'),
    ('eps',         'TLD', '[0.500, 0.900)'),
    ('eps',         'TLD', '[0.900, 1.100)'),
#     ('eps',       'ICANN', '[0.000, 0.100)'),
#     ('eps',       'ICANN', '[0.100, 0.250)'),
#     ('eps',       'ICANN', '[0.250, 0.500)'),
#     ('eps',       'ICANN', '[0.500, 0.900)'),
#     ('eps',       'ICANN', '[0.900, 1.100)'),
#     ('eps',     'PRIVATE', '[0.000, 0.100)'),
#     ('eps',     'PRIVATE', '[0.100, 0.250)'),
#     ('eps',     'PRIVATE', '[0.250, 0.500)'),
#     ('eps',     'PRIVATE', '[0.500, 0.900)'),
#     ('eps',     'PRIVATE', '[0.900, 1.100)'),
#     ('llr',        'ninf',           'NONE'),
#     ('llr',        'ninf',            'TLD'),
#     ('llr',        'ninf',          'ICANN'),
#     ('llr',        'ninf',        'PRIVATE'),
#     ('llr',        'pinf',           'NONE'),
#     ('llr',        'pinf',            'TLD'),
#     ('llr',        'pinf',          'ICANN'),
#     ('llr',        'pinf',        'PRIVATE'),
#     ('llr',        'NONE',              '0'),
#     ('llr',        'NONE',             '100'),
#     ('llr',        'NONE',             '1000'),
#     ('llr',        'NONE',             '1000000'),
#     ('llr',         'TLD',              '0'),
#     ('llr',         'TLD',             '100'),
#     ('llr',         'TLD',             '1000'),
#     ('llr',         'TLD',             '1000000'),
#     ('llr',       'ICANN',              '0'),
#     ('llr',       'ICANN',             '100'),
#     ('llr',       'ICANN',             '1000'),
#     ('llr',       'ICANN',             '1000000'),
#     ('llr',     'PRIVATE',              '0'),
#     ('llr',     'PRIVATE',             '100'),
#     ('llr',     'PRIVATE',             '1000'),
#     ('llr',     'PRIVATE',             '1000000')
]

label_col = ('-', 'source', 'mc')
dataset_cols = x_cols + [label_col]

dataset_cols

[('eps', 'TLD', '[0.000, 0.100)'),
 ('eps', 'TLD', '[0.100, 0.250)'),
 ('eps', 'TLD', '[0.250, 0.500)'),
 ('eps', 'TLD', '[0.500, 0.900)'),
 ('eps', 'TLD', '[0.900, 1.100)'),
 ('-', 'source', 'mc')]

In [159]:
oc = OneClassSVM(nu=0.00005)

X_train = df[dataset_cols].copy()
X_test = df[dataset_cols].copy()

X_train = X_train[X_train[label_col] == 0]
X_train, X_0_test = train_test_split(X_train, test_size=0.5)

X_test = X_test[X_test[label_col] > 0]
X_test = pd.concat([X_test, X_0_test], axis=0)
y_test_true = X_test[label_col].apply(lambda x: 1 if x == 0 else -1)

y_train_true = np.ones(X_train.shape[0])

X_train = X_train.drop(columns=[label_col])
X_test = X_test.drop(columns=[label_col])

y_train_pred = oc.fit_predict(X_train)
# y_train_pred = oc.predict(X_train)
y_test_pred = oc.predict(X_test)

# print(classification_report(y_train_true, y_train_pred))
# print(classification_report(y_test_true, y_test_pred))

print(confusion_matrix(y_train_true, y_train_pred, labels=[1,-1]))
print(confusion_matrix(y_test_true, y_test_pred, labels=[1,-1]))

[[2981    8]
 [   0    0]]
[[  2987      3]
 [131478 129638]]


In [57]:

X_train[y_train_pred == 1]


-                    llr
             -                    TLD
      duration   u   q   r nx      50
3608    10.306  16  50  50  0 -97.643
7406     4.437  23  50  50  0 -36.746
577      8.747  15  50  50  0 -38.051
3835    12.550  21  50  49  0 -72.370
8060    10.157  27  50  50  0 -51.730
...        ...  ..  ..  .. ..     ...
9596    18.669  22  50  50  0 -68.456
5946    20.557  25  50  50  0 -34.554
10693    0.000  24  50  46  0 -63.290
11162    0.000  25  50  35  0 -70.668
11228    0.000  28  50  52  0 -80.603

[596 rows x 6 columns]

In [58]:

oc = OneClassSVM()

# X_train = X_train[y_train_pred == 1]
y_train_true = np.ones(X_train[y_train_pred == 1].shape[0])

y_train_pred = oc.fit_predict(X_train[y_train_pred == 1])

print(confusion_matrix(y_train_true, y_train_pred, labels=[1,-1]))

[[298 298]
 [  0   0]]


In [96]:
X = df[labels == 0]
X

l1         -                                                       
          l2    source                                                       
          l3 manyindex        galaxy                                  name   
31        31         2  stratosphere  12_2013-12-17_capture1.only-dns.pcap  \
32        32         2  stratosphere  12_2013-12-17_capture1.only-dns.pcap   
33        33         2  stratosphere  12_2013-12-17_capture1.only-dns.pcap   
34        34         2  stratosphere  12_2013-12-17_capture1.only-dns.pcap   
35        35         2  stratosphere  12_2013-12-17_capture1.only-dns.pcap   
...      ...       ...           ...                                   ...   
11257  11257        32  stratosphere        22_2017-05-02_kali-normal.pcap   
11258  11258        32  stratosphere        22_2017-05-02_kali-normal.pcap   
11259  11259        32  stratosphere        22_2017-05-02_kali-normal.pcap   
11260  11260        32  stratosphere        22_2017-05-02_kali-normal.pcap   
11261  11261        32  stratosphere        22_2017-05-02_kali-normal.pcap   

                                            ...       llr                       
                    -                       ...       TLD               ICANN   
       id bc mc index n_message fn_req_min  ...        15        50         0   
31      9  0  0     0       320          0  ... -1405.590 -1405.590  -845.654  \
32      9  0  0     1       336         50  ... -1461.434 -1461.434  -898.159   
33      9  0  0     2       384        100  ... -1661.061 -1661.061 -1013.272   
34      9  0  0     3       376        150  ... -1590.254 -1590.254  -988.605   
35      9  0  0     4       384        200  ... -1658.997 -1658.997 -1009.987   
...    .. .. ..   ...       ...        ...  ...       ...       ...       ...   
11257  13  0  0  1036       152      51800  ...     0.000     0.000  -230.909   
11258  13  0  0  1037       104      51850  ...   -16.611   -16.611  -126.462   
11259  13  0  0  1038       176      51900  ...   -59.571   -59.571  -225.193   
11260  13  0  0  1039       216      51950  ...   -22.778   -22.778  -325.789   
11261  13  0  0  1040       144      52000  ...   -34.062   -34.062  -218.858   

                                                                         
                                     PRIVATE                             
             10        15        50        0       10       15       50  
31     -845.654  -845.654  -845.654 -557.478 -557.478 -557.478 -557.478  
32     -898.159  -898.159  -898.159 -580.093 -580.093 -580.093 -580.093  
33    -1013.272 -1013.272 -1013.272 -665.097 -665.097 -665.097 -665.097  
34     -967.213  -967.213  -967.213 -662.137 -649.203 -649.203 -649.203  
35    -1009.987 -1009.987 -1009.987 -652.982 -652.982 -652.982 -652.982  
...         ...       ...       ...      ...      ...      ...      ...  
11257     0.000     0.000     0.000 -203.955    0.000    0.000    0.000  
11258    14.333    14.333    14.333 -111.523   14.151   14.151   14.151  
11259   -12.190   -12.190   -12.190 -169.303   28.537   28.537   28.537  
11260   -14.694   -14.694   -14.694 -322.485  -11.343  -11.343  -11.343  
11261   -30.221   -30.221   -30.221 -211.444  -31.820  -31.820  -31.820  

[5979 rows x 66 columns]